### ISSUE TITLE
latest version of repo structures [1.17.1] crashes

### ISSUE THREAD

**Issue by red2blue** [TelepathicGrunt/RepurposedStructures#116]
Not compatiable with Architectury. causing crashes .

Reason I know this is because I disabled mod by mod to find out the cause, Not Enough Crashes said it was arcitechtuary however, once I disabled the updated rep struct. the server turned on. The previous version worked fine.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/25/21, 12:33 PM
Description: mouseClicked event handler

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.25)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:375)
	at jdk.proxy3.$Proxy91.<clinit>(Unknown Source)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1044)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1030)
	at dev.architectury.event.EventFactory.lambda$createLoop$0(EventFactory.java:53)
	at dev.architectury.event.EventFactory$EventImpl.update(EventFactory.java:239)
	at dev.architectury.event.EventFactory$EventImpl.invoker(EventFactory.java:205)
	at net.minecraft.client.MinecraftClient.handler$zhl000$handleLogin(MinecraftClient:3094)
	at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient:2202)
	at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient:2185)
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:2028)
	at net.minecraft.client.MinecraftClient.method_29608(MinecraftClient:2017)
	at net.minecraft.client.MinecraftClient.method_29600(MinecraftClient:2110)
	at net.minecraft.client.gui.screen.BackupPromptScreen.method_19792(BackupPromptScreen:40)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27)
	at net.minecraft.client.Mouse.method_1611(Mouse:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:190)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1140)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method repurposedstructures_makeFileNameLonger(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in repurposed_structures.mixins.json:blocks.StructureBlockScreenMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap repurposed_structures_fabric-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 50 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at jdk.proxy3/jdk.proxy3.$Proxy91.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1044)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1030)
	at dev.architectury.event.EventFactory.lambda$createLoop$0(EventFactory.java:53)
	at dev.architectury.event.EventFactory$EventImpl.update(EventFactory.java:239)
	at dev.architectury.event.EventFactory$EventImpl.invoker(EventFactory.java:205)
	at net.minecraft.class_310.handler$zhl000$handleLogin(class_310.java:3094)
	at net.minecraft.class_310.method_18096(class_310.java:2202)
	at net.minecraft.class_310.method_18099(class_310.java:2185)
	at net.minecraft.class_310.method_29610(class_310.java:2028)
	at net.minecraft.class_310.method_29608(class_310.java:2017)
	at net.minecraft.class_310.method_29600(class_310.java:2110)
	at net.minecraft.class_405.method_19792(class_405.java:40)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_405
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.25)
	at java.lang.Thread.getStackTrace(Thread.java:1596)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:523)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:198)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:169)
	at net.minecraft.client.resource.ResourceReloadLogger.addReloadSection(ResourceReloadLogger:49)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient:2406)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.client.MinecraftClient.modify$cfo000$onCrash(MinecraftClient:14099)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, charmonium/journeyman
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$cfo000$onCrash(class_310.java:14099)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 362760768 bytes (345 MiB) / 1786773504 bytes (1704 MiB) up to 10166992896 bytes (9696 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e87
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.40
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 38221.95
	Virtual memory used (MB): 30708.16
	Swap memory total (MB): 5522.48
	Swap memory used (MB): 965.02
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9696m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		advancements-enlarger: Advancements Enlarger 0.2.4
		ambientenvironment: Ambient Environment fabric-1.17.1-6.0.13
		amecsapi: Amecs API 1.1.5+mc21w16a
		antiqueatlas: Antique Atlas 6.0.0-fabric-mc1.17.1
		apoli: Apoli 1.0.4
		appleskin: AppleSkin mc1.17-2.1.0
		aqupd: Caracal mob 1.17-1.2.2
		architectury: Architectury 2.2.21
		backslot: BackSlot 1.2.0
		backslotaddon: BackSlot Addon 1.0.5
		bclib: BCLib 0.2.4
		better_wandering_trader: Better Wandering Trader 1.7.0
		betterbiomeblend: Better Biome Blend 1.17.0-1.2.3-fabric
		betterend: Better End 0.10.5-pre
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1
		blockus: Blockus 2.2.7+1.17.1
		calio: Calio 1.0.2
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components: Cardinal Components API 3.0.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.0.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.0.1
		cardinal-components-level: Cardinal Components API (world saves) 3.0.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.0.1
		cardinal-components-util: Cardinal Components API (utilities) 3.0.1
		cardinal-components-world: Cardinal Components API (worlds) 3.0.1
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		chesttracker: Chest Tracker 1.0.11
		cleancut: CleanCut 1.17-4.0-fabric
		cleardespawn: Clear Despawn 1.17.1-fabric0.36.1-1.1.1
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		croptopia: Croptopia 1.5.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portal Api 0.0.1-beta38-1.17
		dankstorage: Dank Storage 2.1-1.17.1
		detailab: Detail Armor Bar 1.2.3+1.17.1
		dual_riders: DualRiders 1.0.5
		enchant_giver: Enchant Giver 1.1.0
		enchantmentdescriptions: Enchantment Descriptions 3.0.12
		expandedstorage: Expanded Storage 7.0.0-alpha.37
		fabric: Fabric API 0.37.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricenchantments: Fabric Enchantments 0.3.2
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.12.1
		fasttransferlib: Fast Transfer Lib 0.5.5
		ferritecore: FerriteCore 3.0.1
		gamemodeoverhaul: GamemodeOverhaul 1.1.0
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.10
		gobber2: Gobber2 2.4.32
		hookshot: Hookshot 16.0
		horseinfo: Horse Info 0.3.0-1.17
		iknowwhatimdoing: I Know What I'm Doing 3.1.0
		illuminations: Illuminations 1.6.2
		inventoryprofilesnext: Inventory Profiles Next 0.8.4
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kibe: Kibe 1.8-BETA+1.17
		ksrch: Keybind Search 1.0.0
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lazydfu: LazyDFU 0.1.2
		libblockattributes: LibBlockAttributes 0.8.17003
		libblockattributes_core: LibBlockAttributes (Core) 0.8.17003
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.17003
		libblockattributes_items: LibBlockAttributes (Items) 0.8.17003
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.4+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.3
		logical_zoom: Logical Zoom 0.0.11
		ltr: LilTaterReloaded 1.1.14+1.17
		malilib: MaLiLib 0.10.0-dev.24
		mcda: MC Dungeons Armors 1.7.5
		mcdw: MC Dungeons Weapons 3.3.4
		megane: megane 5.1.1
		megane-base: megane-base 5.1.1
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.1.1+0.4.2
		megane-kibe: megane-kibe 5.1.1+1.7.2-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.1.1+0.9.0
		megane-runtime: megane-runtime 5.1.1
		megane-team-reborn-energy: megane-team-reborn-energy 5.1.1+0.1.1
		megane-tech-reborn: megane-tech-reborn 5.1.1+5.0.2-beta-build.38
		megane-vanilla: megane-vanilla 5.1.1+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.1.1+1.1.1
		minecraft: Minecraft 1.17.1
		mining_dims: Mining Dimensions 1.1.9
		modmenu: Mod Menu 2.0.4
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		naturescompass: Nature's Compass 1.17.1-2.0.0-fabric
		noanglebrackets: NoAngleBrackets 1.1.0
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_objenesis_objenesis: objenesis 3.2
		origins: Origins 1.0.3
		origins-classes: Origins: Classes 1.2.2
		plantinajar: Plant In A Jar 2.2.2
		playerabilitylib: Pal 1.3.0
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		ratsmischief: Rat's Mischief 1.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.5-beta+build.85
		repurposed_structures: Repurposed Structures 2.1.5+1.17.1
		resourceful_tools: Resourceful Tools 1.1.18
		right-click-clear: Right Click Clear 2.0.3
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		schmucks: Schmucks 1.4.0
		simple_backpack: SimpleBackpack 1.1.13
		spruceui: SpruceUI 3.2.0+1.17
		stoneholm: Stoneholm 1.3
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 5.0.5-beta+build.85
		the_bumblezone: The Bumblezone - Fabric 3.0.7+1.17.1
		torcherino: Torcherino 15.0.0-alpha.3
		trinkets: Trinkets 3.0.2
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		waterdripsound: Drip Sounds 1.17-0.2.2
		waystones: Waystones 2.0.2
		whereisit: Where Is It 1.13.3
		winged: Winged Mod 1.17.1-3.0.0
		wirelessnetworks: Wireless Networks 1.1.2
		witherite: Witherite 0.0.8-hotfix
		wthit: wthit 3.8.0
		xhp: xhp 1.0.9
		yungsapi: YUNG's API 1.17-Fabric-13
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2080/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.41, NVIDIA Corporation
	Window size: 3440x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods, charmonium/journeyman, charmonium/journeyman
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Loader (fabricloader), Architectury (architectury)

**Comment by itsdinkd** [comment]
I apologize. This is for the fabric version 2.15
