### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by SSKirillSS** [TelepathicGrunt/RepurposedStructures#148]
Mod version and other details inside this log file: https://pastebin.com/KygV9xQJ

Issue is pretty simple - mod doesn't load on the server.

**Comment by TelepathicGrunt** [comment]
This does not appear to be caused by repurposed structures. see this line?
```
Caused by 0: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: com.litewolf101.illagers_plus.objects.entity.EntityIceSpike.<init>(EntityType,World)void/newInvokeSpecial
		at com.litewolf101.illagers_plus.init.EntityInit.<clinit>(EntityInit.java:40) ~[illagers_plus:1.16.4v1.7] {re:classloading}
```
		
It appears to be an issue with illagers+. Try reporting the issue to them so they can try and fix it. I wonder what happened that caused that issue with them. I think they are calling some client side code somehow and that is making the mod die on servers because servers do not have client side code

```
Caused by 2: java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound
		at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_291] {}
		at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_291] {}
		at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_291] {}
		at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_291] {}
		at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_291] {}
		at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_291] {}
		at com.litewolf101.illagers_plus.init.EntityInit.<clinit>(EntityInit.java:40) ~[illagers_plus:1.16.4v1.7] {re:classloading}
```

**Comment by SSKirillSS** [comment]
Oh... I just missclicked to the wrong mod github and didn't double-checked it. Sorry :D
