### ISSUE TITLE
[1.18.1 Fabric] unable to start server

### ISSUE THREAD

**Issue by itsdinkd** [TelepathicGrunt/RepurposedStructures#174]
Updated to latest repurposed structures, launched a server locally to test modpack update, and it failed to start.
 

```java
[14:23:01] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.nio.file.FileSystemException: C:\Users\CC\Downloads\aqm2-server\t\kubejs\data\repurposed_structures\pool_additions\villages\jungle: The process cannot access the file because it is being used by another process
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.18) ~[?:?]
        at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
        at net.minecraft.server.Main.main(Main:163) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: java.io.UncheckedIOException: java.nio.file.FileSystemException: C:\Users\C\Downloads\aqm2-server\t\kubejs\data\repurposed_structures\pool_additions\villages\jungle: The process cannot access the file because it is being used by another process
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(Unknown Source) ~[?:?]
        at java.nio.file.FileTreeIterator.hasNext(Unknown Source) ~[?:?]
        at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at dev.latvian.mods.kubejs.script.data.KubeJSResourcePack.lambda$getResources$6(KubeJSResourcePack.java:148) ~[kubejs-fabric-1801.4.1-build.271.jar:?]
        at dev.latvian.mods.kubejs.util.UtilsJS.tryIO(UtilsJS.java:84) ~[kubejs-fabric-1801.4.1-build.271.jar:?]
        at dev.latvian.mods.kubejs.script.data.KubeJSResourcePack.findResources(KubeJSResourcePack.java:134) ~[kubejs-fabric-1801.4.1-build.271.jar:?]
        at net.minecraft.resource.NamespaceResourceManager.findResources(NamespaceResourceManager:156) ~[?:?]
        at net.minecraft.resource.ReloadableResourceManagerImpl.findResources(ReloadableResourceManagerImpl:95) ~[?:?]
        at dev.fulmineo.companion_bats.data.ServerDataManager$1.reload(ServerDataManager.java:53) ~[companion-bats-fabric-1.18.7.jar:?]
        at net.minecraft.resource.SynchronousResourceReloader.method_29490(SynchronousResourceReloader:15) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.nio.file.FileSystemException: C:\Users\cc\Downloads\aqm2-server\t\kubejs\data\repurposed_structures\pool_additions\villages\jungle: The process cannot access the file because it is being used by another process
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsDirectoryStream.<init>(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(Unknown Source) ~[?:?]
        at java.nio.file.Files.newDirectoryStream(Unknown Source) ~[?:?]
        at java.nio.file.FileTreeWalker.visit(Unknown Source) ~[?:?]
        at java.nio.file.FileTreeWalker.next(Unknown Source) ~[?:?]
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(Unknown Source) ~[?:?]
        at java.nio.file.FileTreeIterator.hasNext(Unknown Source) ~[?:?]
        at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at dev.latvian.mods.kubejs.script.data.KubeJSResourcePack.lambda$getResources$6(KubeJSResourcePack.java:148) ~[kubejs-fabric-1801.4.1-build.271.jar:?]
        at dev.latvian.mods.kubejs.util.UtilsJS.tryIO(UtilsJS.java:84) ~[kubejs-fabric-1801.4.1-build.271.jar:?]
        at dev.latvian.mods.kubejs.script.data.KubeJSResourcePack.findResources(KubeJSResourcePack.java:134) ~[kubejs-fabric-1801.4.1-build.271.jar:?]
        at net.minecraft.resource.NamespaceResourceManager.findResources(NamespaceResourceManager:156) ~[?:?]
        at net.minecraft.resource.ReloadableResourceManagerImpl.findResources(ReloadableResourceManagerImpl:95) ~[?:?]
        at dev.fulmineo.companion_bats.data.ServerDataManager$1.reload(ServerDataManager.java:53) ~[companion-bats-fabric-1.18.7.jar:?]
        at net.minecraft.resource.SynchronousResourceReloader.method_29490(SynchronousResourceReloader:15) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
        at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]

```

**Comment by itsdinkd** [comment]
I am loading the Repurposed structure addons that you provided. i think that is the issuehere

**Comment by itsdinkd** [comment]
this is the file that its saying already is running

```java
{
  "name": "repurposed_structures:villages/jungle/houses",
  "fallback": "repurposed_structures:villages/jungle/terminators",
  "elements": [
    {
      "weight": 1,
      "element": {
        "location": "morevillagers:village/jungle/jungle_engineer",
        "processors": "repurposed_structures:villages/jungle/mossify",
        "projection": "rigid",
        "element_type": "minecraft:legacy_single_pool_element"
      }
    },
    {
      "weight": 4,
      "element": {
        "location": "morevillagers:village/jungle/jungle_florist",
        "processors": "repurposed_structures:villages/jungle/mossify",
        "projection": "rigid",
        "element_type": "minecraft:legacy_single_pool_element"
      }
    },
    {
      "weight": 2,
      "element": {
        "location": "morevillagers:village/jungle/jungle_hunter",
        "processors": "repurposed_structures:villages/jungle/mossify",
        "projection": "rigid",
        "element_type": "minecraft:legacy_single_pool_element"
      }
    },
    {
      "weight": 2,
      "element": {
        "location": "morevillagers:village/jungle/jungle_oceanographer",
        "processors": "repurposed_structures:villages/jungle/mossify",
        "projection": "rigid",
        "element_type": "minecraft:legacy_single_pool_element"
      }
    },
    {
      "weight": 2,
      "element": {
        "location": "morevillagers:village/jungle/jungle_woodworker",
        "processors": "repurposed_structures:villages/jungle/mossify",
        "projection": "rigid",
        "element_type": "minecraft:legacy_single_pool_element"
      }
    }
  ]
}

```

**Comment by TelepathicGrunt** [comment]
this looks more like a kubejs issue. Datapacks alone in the world's datapack folder should load just fine. Or using stuff like OpenLoader or Global Resource & Datapack mod should work just fine. It doesn't say what the file is being used by. 

How do you setup kubejs? i have never used it before I am not sure how to try and reproduce it with kubejs.

**Comment by TelepathicGrunt** [comment]
Figured out kubejs. I shoved my datapack into it and was able to enter a world just fine 
![image](https://user-images.githubusercontent.com/40846040/148703980-3cfeaabe-7086-488e-b268-e6f34f58ab80.png)


Try and make sure your server doesnt have a hidden stuck minecraft process still running by mistake. That could cause this issue.

**Comment by itsdinkd** [comment]
So I think some how MoreVillagers got deleted when I tested. Would that be the reason why?

**Comment by TelepathicGrunt** [comment]
Yeah it would be. Without the mod on, the mod compat datapack will explode lol

**Comment by TelepathicGrunt** [comment]
gonna close this as we determined the issue was the more villager mod was off while the more villager datapack was on.
