### ISSUE TITLE
[1.18.2 Better Strongholds ResourcePack] Invalid datapack?

### ISSUE THREAD

**Issue by itsdinkd** [TelepathicGrunt/RepurposedStructures#203]
So, not sure why but I just started receiving this in my test world. I did edit better strongholds loot tables and placed the modifications in a datapack, but since then, I am getting this error. I tested my edits in the loot tables using jsonlint and they all passed so it should not be affecting it. 

Full log: https://gist.github.com/itsdinkd/7c1ba26ede9e4d25b0f4945ba048aa64
```java
[09:30:42] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/processor_list]: [betterstrongholds:end/main, betterstrongholds:end/rooms/grand_library, betterstrongholds:nether/main, betterstrongholds:nether/rooms/grand_library]
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient:2124) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1972) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1937) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.start(WorldListWidget:431) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.play(WorldListWidget:340) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.mouseClicked(WorldListWidget:271) ~[?:?]
	at net.minecraft.client.gui.widget.EntryListWidget.mouseClicked(EntryListWidget:359) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:492) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:204) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:310) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1147) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.2.jar:?]
Caused by: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/processor_list]: [betterstrongholds:end/main, betterstrongholds:end/rooms/grand_library, betterstrongholds:nether/main, betterstrongholds:nether/rooms/grand_library]
	at net.minecraft.util.registry.SimpleRegistry.freeze(SimpleRegistry:325) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistryManager$Entry.freeze(DynamicRegistryManager:121) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistryManager$ImmutableImpl.<init>(DynamicRegistryManager:161) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistryManager.toImmutable(DynamicRegistryManager:322) ~[?:?]
	at net.minecraft.server.SaveLoader$SavePropertiesSupplier.method_40433(SaveLoader:92) ~[?:?]
	at net.minecraft.server.SaveLoader.ofLoaded(SaveLoader:40) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient:2122) ~[?:?]
	... 28 more
```

**Comment by itsdinkd** [comment]
Nevermind, I think I found the problem.
