### ISSUE TITLE
Crashed in 1.16.5

### ISSUE THREAD

**Issue by githubuser98k** [TelepathicGrunt/RepurposedStructures#245]
--- Minecraft Crash Report ----
// My bad.

Time: 11/28/22 8:29 PM
Description: Rendering overlay

com.electronwill.nightconfig.core.io.WritingException: An I/O error occured
	at com.electronwill.nightconfig.core.io.ConfigWriter.write(ConfigWriter.java:90) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.save(WriteSyncFileConfig.java:61) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.save(AutosaveCommentedFileConfig.java:80) ~[core-3.6.3.jar:?] {}
	at net.minecraftforge.fml.config.ModConfig.save(ModConfig.java:80) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:93) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:69) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker$$Lambda$7471/135814837.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:69) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:195) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$startModLoading$7(ClientModLoader.java:118) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$7464/1001140012.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:109) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2926/2021979938.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:118) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onResourceReload$2(ClientModLoader.java:100) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$7452/1093359629.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:109) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2926/2021979938.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}
Caused by: java.nio.file.FileSystemException: C:\Users\Topet\curseforge\minecraft\Instances\test modpack\config\repurposed_structures-forge\ruined_portals.toml: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_51] {}
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_51] {}
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:1.8.0_51] {}
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230) ~[?:1.8.0_51] {}
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[?:1.8.0_51] {}
	at java.nio.file.Files.newOutputStream(Files.java:216) ~[?:1.8.0_51] {}
	at com.electronwill.nightconfig.core.io.ConfigWriter.write(ConfigWriter.java:87) ~[core-3.6.3.jar:?] {}
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.electronwill.nightconfig.core.io.ConfigWriter.write(ConfigWriter.java:90) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.save(WriteSyncFileConfig.java:61) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.save(AutosaveCommentedFileConfig.java:80) ~[core-3.6.3.jar:?] {}
	at net.minecraftforge.fml.config.ModConfig.save(ModConfig.java:80) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:93) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:69) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker$$Lambda$7471/135814837.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:69) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:195) ~[?:?] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:484) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$465/934085675.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 752449992 bytes (717 MB) / 1930428416 bytes (1841 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 20
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |COMMON_SET|Manifest: NOSIGNATURE
		litewolfcore-1.16.5v1.0.1.jar                     |LiteWolf Core                 |litewolfcore                  |1.16.5v1.0          |COMMON_SET|Manifest: NOSIGNATURE
		mowziesmobs-1.5.27.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.27              |COMMON_SET|Manifest: NOSIGNATURE
		BetterDungeons-1.16.4-1.2.1.jar                   |YUNG's Better Dungeons        |betterdungeons                |1.16.4-1.2.1        |COMMON_SET|Manifest: NOSIGNATURE
		UnionLib-1.16.5-3.3.7.jar                         |UnionLib                      |unionlib                      |3.3.7               |COMMON_SET|Manifest: NOSIGNATURE
		player-animation-lib-forge-0.4.0+1.16.5.jar       |Player Animator               |playeranimator                |0.4.0+1.16.5        |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.153.jar                          |Just Enough Items             |jei                           |7.7.1.153           |COMMON_SET|Manifest: NOSIGNATURE
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |COMMON_SET|Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.1.jar                   |Abnormals Core                |abnormals_core                |3.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		stalwart-dungeons-1.16.5-1.1.7.jar                |Stalwart Dungeons             |stalwart_dungeons             |1.1.7               |COMMON_SET|Manifest: NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-6.0.0.28.jar                               |Clumps                        |clumps                        |6.0.0.28            |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.28.3_Forge_1.16.5.jar            |Xaero's World Map             |xaeroworldmap                 |1.28.3              |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.16.5-4.7.0.jar                          |Placebo                       |placebo                       |4.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		comforts-forge-1.16.5-4.0.1.5.jar                 |Comforts                      |comforts                      |1.16.5-4.0.1.5      |COMMON_SET|Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |COMMON_SET|Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |COMMON_SET|Manifest: NOSIGNATURE
		DungeonCrawl-1.16.5-2.3.9.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.9               |COMMON_SET|Manifest: NOSIGNATURE
		u_team_core-1.16.5-3.2.1.229.jar                  |U Team Core                   |uteamcore                     |3.2.1.229           |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		iceandfire-2.1.11-1.16.5.jar                      |Ice and Fire                  |iceandfire                    |2.1.11-1.16.5       |COMMON_SET|Manifest: NOSIGNATURE
		ToastControl-1.16.5-4.4.0.jar                     |Toast Control                 |toastcontrol                  |4.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		FpsReducer-forge-1.24-mc1.16.5.jar                |FPS Reducer                   |fpsreducer                    |1.24-mc1.16.5       |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.128.jar         |Just Enough Resources         |jeresources                   |0.12.1.128          |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |COMMON_SET|Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.8.jar                    |Structure Gel API             |structure_gel                 |1.7.8               |COMMON_SET|Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.21.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |COMMON_SET|Manifest: NOSIGNATURE
		DungeonsArise-1.16.5-2.1.49-beta.jar              |When Dungeons Arise           |dungeons_arise                |2.1.49              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |COMMON_SET|Manifest: NOSIGNATURE
		useful_backpacks-1.16.5-1.12.1.103.jar            |Useful Backpacks              |usefulbackpacks               |1.12.1.103          |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		repurposed_structures_forge-3.4.7+1.16.5.jar      |Repurposed Structures         |repurposed_structures         |3.4.7+1.16.5        |COMMON_SET|Manifest: NOSIGNATURE
		forgedfabric-0.0.7+1.16.jar                       |ForgedFabric API              |forgedfabric                  |NONE                |COMMON_SET|Manifest: NOSIGNATURE
		bettercombat-1.4.5.3+1.16.jar                     |Better Combat                 |bettercombat                  |1.4.5.3+1.16        |COMMON_SET|Manifest: NOSIGNATURE
		totw_additions-1.1.0.jar                          |Towers of the Wild: Additions |totw_additions                |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.16.4-2.8.3.jar                             |Jade                          |jade                          |2.8.3               |COMMON_SET|Manifest: NOSIGNATURE
		endrem-5.0.3-R-1.16.5.jar                         |End Remastered                |endrem                        |5.0.3-R-1.16.5      |COMMON_SET|Manifest: NOSIGNATURE
		ShoulderSurfing-Forge-1.16.5-2.2.16.jar           |Shoulder Surfing              |shouldersurfing               |1.16.5-2.2.16       |COMMON_SET|Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBridges-Forge-1.16.4-1.0.1.jar               |YUNG's Bridges                |yungsbridges                  |1.16.4-1.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		towers_of_the_wild-1.16.3-2.1.0.1.jar             |Towers Of The Wild            |towers_of_the_wild            |1.16.3-2.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |COMMON_SET|Manifest: NOSIGNATURE
		dungeons_enhanced-1.16.5-1.8.1.jar                |Dungeons Enhanced             |dungeons_enhanced             |1.8.1               |COMMON_SET|Manifest: NOSIGNATURE
		betterfpsdist-1.2.jar                             |betterfpsdist mod             |betterfpsdist                 |1.2                 |COMMON_SET|Manifest: NOSIGNATURE
		playerex-1.1.8-1.16.5.jar                         |Player Ex                     |playerex                      |1.1.8               |COMMON_SET|Manifest: NOSIGNATURE
		L_Enders Cataclysm-0.40-1.16.5.jar                |Cataclysm Mod                 |cataclysm                     |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |COMMON_SET|Manifest: NOSIGNATURE
		SpartanShields-1.16.5-2.1.2.jar                   |Spartan Shields               |spartanshields                |2.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		savageandravage-1.16.5-3.2.0.jar                  |Savage & Ravage               |savageandravage               |3.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_22.16.2_Forge_1.16.5.jar           |Xaero's Minimap               |xaerominimap                  |22.16.2             |COMMON_SET|Manifest: NOSIGNATURE
		FastWorkbench-1.16.5-4.6.2.jar                    |Fast Workbench                |fastbench                     |4.6.2               |COMMON_SET|Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.41.jar                   |Polymorph                     |polymorph                     |1.16.5-0.41         |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |COMMON_SET|Manifest: NOSIGNATURE
		Quark-r2.4-322.jar                                |Quark                         |quark                         |r2.4-322            |COMMON_SET|Manifest: NOSIGNATURE
		YungsExtras-Forge-1.16.4-1.0.jar                  |YUNG's Extras                 |yungsextras                   |Forge-1.16.4-1.0    |COMMON_SET|Manifest: NOSIGNATURE
		Survive-1.16.5-3.4.8.jar                          |Survive                       |survive                       |1.16.5-3.4.8        |COMMON_SET|Manifest: NOSIGNATURE
		ftb-ultimine-forge-1605.3.1-build.45.jar          |FTB Ultimine                  |ftbultimine                   |1605.3.1-build.45   |COMMON_SET|Manifest: NOSIGNATURE
		FastFurnace-1.16.5-4.5.0.jar                      |FastFurnace                   |fastfurnace                   |4.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		SpartanWeaponry-1.16.5-2.2.0-rc-2.jar             |Spartan Weaponry              |spartanweaponry               |2.2.0 Release Candid|COMMON_SET|Manifest: NOSIGNATURE
		mvs-2.6.1.jar                                     |Moog's Voyager Structures     |mvs                           |2.6.1               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-1.32.66.jar                          |Architectury                  |architectury                  |1.32.66             |COMMON_SET|Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.4-build.90.jar           |FTB Library                   |ftblibrary                    |1605.3.4-build.90   |COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.4.0.jar                |AppleSkin                     |appleskin                     |2.4.0+mc1.16.4      |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-2.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.1               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		cloth-config-4.16.91-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.16.91             |COMMON_SET|Manifest: NOSIGNATURE
		combatroll-1.0.8.2+1.16.jar                       |Combat Roll                   |combatroll                    |1.0.8.2+1.16        |COMMON_SET|Manifest: NOSIGNATURE
		byg-1.3.6.jar                                     |Oh The Biomes You'll Go       |byg                           |1.3.4               |COMMON_SET|Manifest: NOSIGNATURE
		illagers_plus-1.16.5v1.0.2.jar                    |Illagers+                     |illagers_plus                 |1.16.5v1.0.2        |COMMON_SET|Manifest: NOSIGNATURE
		expandability-2.0.1-forge.jar                     |ExpandAbility                 |expandability                 |2.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		valhelsia_core-16.0.15.jar                        |Valhelsia Core                |valhelsia_core                |16.0.15             |COMMON_SET|Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.6.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.6        |COMMON_SET|Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.2.jar                    |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.2       |COMMON_SET|Manifest: NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta12.jar          |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta12 |COMMON_SET|Manifest: NOSIGNATURE
		DynamicTreesBOP-1.16.5-2.0.9.jar                  |Dynamic Trees for Biomes o' Pl|dtbop                         |1.16.5-2.0.9        |COMMON_SET|Manifest: NOSIGNATURE
		DynamicTreesBYG-1.16.5-1.0.2.jar                  |Dynamic Trees for BYG         |dtbyg                         |1.16.5-1.0.2        |COMMON_SET|Manifest: NOSIGNATURE
		DynamicTreesQuark-1.16.5-2.1.3.jar                |Dynamic Trees for Quark       |dtquark                       |1.16.5-2.1.3        |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.104.jar                 |GeckoLib                      |geckolib3                     |3.0.104             |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 5aeb6891-0040-4aaa-b423-afeab62b0040
	Launched Version: forge-36.2.39
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) Iris(R) Xe Graphics GL version 4.6.0 - Build 30.0.101.1368, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700H

**Comment by githubuser98k** [comment]
Can you fingue out why this happened

**Comment by TelepathicGrunt** [comment]
Just fyi, I'm not supporting 1.16.5 anymore. But anyway, your issue is this: 
`Caused by: java.nio.file.FileSystemException: C:\Users\Topet\curseforge\minecraft\Instances\test modpack\config\repurposed_structures-forge\ruined_portals.toml: The process cannot access the file because it is being used by another process.`

Something is accessing and holding onto config files in a way that Forge cannot read/write to it. Forge is the one that handles the config stuff from my mod back then. You can try opening task manager and make sure all Minecraft instances are closed and such or rebooting computer to make sure nothing is holding files. Can also try deleting the config files to see if having forge make it will resolve issue. 

That's the best advice I can give and this isn't something I could even fix anyway even if it happened on 1.19.2. This is something with the processes on your computer
