### ISSUE TITLE
6.3.14 crashes on Quilt

### ISSUE THREAD

**Issue by Zekiu** [TelepathicGrunt/RepurposedStructures#260]
Crash : 
```
org.quiltmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: com/telepathicgrunt/repurposedstructures/utils/fabric/PlatformHooksImpl
        at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:425) ~[quilt-loader-0.17.11.jar:?]
        at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) ~[quilt-loader-0.17.11.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) ~[quilt-loader-0.17.11.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:63) ~[quilt-loader-0.17.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/telepathicgrunt/repurposedstructures/utils/fabric/PlatformHooksImpl
        at com.telepathicgrunt.repurposedstructures.utils.PlatformHooks.isModLoaded(PlatformHooks.java) ~[repurposed_structures-6.3.14+1.19.3-quilt.jar:?]
        at com.telepathicgrunt.repurposedstructures.RepurposedStructures.init(RepurposedStructures.java:38) ~[repurposed_structures-6.3.14+1.19.3-quilt.jar:?]
        at com.telepathicgrunt.repurposedstructures.quilt.RepurposedStructuresQuilt.onInitialize(RepurposedStructuresQuilt.java:31) ~[repurposed_structures-6.3.14+1.19.3-quilt.jar:?]
        at net.minecraft.class_2966.redirect$dcc000$initialize(class_2966.java:1040) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:61) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:99) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) ~[quilt-loader-0.17.11.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: com.telepathicgrunt.repurposedstructures.utils.fabric.PlatformHooksImpl
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159) ~[quilt-loader-0.17.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.telepathicgrunt.repurposedstructures.utils.PlatformHooks.isModLoaded(PlatformHooks.java) ~[repurposed_structures-6.3.14+1.19.3-quilt.jar:?]
        at com.telepathicgrunt.repurposedstructures.RepurposedStructures.init(RepurposedStructures.java:38) ~[repurposed_structures-6.3.14+1.19.3-quilt.jar:?]
        at com.telepathicgrunt.repurposedstructures.quilt.RepurposedStructuresQuilt.onInitialize(RepurposedStructuresQuilt.java:31) ~[repurposed_structures-6.3.14+1.19.3-quilt.jar:?]
        at net.minecraft.class_2966.redirect$dcc000$initialize(class_2966.java:1040) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:61) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:99) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) ~[quilt-loader-0.17.11.jar:?]
        ... 7 more
```
I don't know if it happens on any other mod loader as I haven't tested them

Minecraft: 1.19.3
Quilt: 0.17.11

latest.log: 
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/10726354/latest.log)

Environment: 
```
Linux PC 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Java: 
```
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, sharing) 
```

**Comment by TelepathicGrunt** [comment]
Fixed in v6.3.15 hopefully lol
