### ISSUE TITLE
Quilt Server 1.20 - cannot invoke "org.quiltmc.loader.impl.gui.QuiltForkComms.send(org.quiltmc.loader.api.LoaderValue)"

### ISSUE THREAD

**Issue by Magicrafter13** [TelepathicGrunt/RepurposedStructures#288]
Adding this mod to my server (latest version/download) stops the server from even starting up. Using latest version of mod available on Modrinth (as of Saturday). `repurposed_structures-7.0.0%2B1.20-quilt.jar`
```
---- Quilt Loader: Critial Error Report ----
Date/Time: 2023/06/12 14:39:05.2692

-- Error 2 --

Unhandled Throwable!

java.lang.NullPointerException: Cannot invoke "org.quiltmc.loader.impl.gui.QuiltForkComms.send(org.quiltmc.loader.api.LoaderValue)" because "org.quiltmc.loader.impl.gui.QuiltFork.COMMS" is null
        at org.quiltmc.loader.impl.gui.QuiltFork.uploadIcon(QuiltFork.java:149)
        at org.quiltmc.loader.impl.gui.GuiManagerImpl.allocateIcons(GuiManagerImpl.java:89)
        at org.quiltmc.loader.impl.gui.GuiManagerImpl.allocateIcon(GuiManagerImpl.java:83)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper.setIconFromMod(SolverErrorHelper.java:354)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper.access$000(SolverErrorHelper.java:57)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper$DependencyError.report(SolverErrorHelper.java:595)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper.reportErrors(SolverErrorHelper.java:68)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.handleSolverFailure(QuiltPluginManagerImpl.java:1452)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runSingleCycle(QuiltPluginManagerImpl.java:1348)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runInternal(QuiltPluginManagerImpl.java:1253)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.run(QuiltPluginManagerImpl.java:708)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.runPlugins(QuiltLoaderImpl.java:512)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:293)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:285)
        at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:147)
        at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:66)


-- Error 1 --

The plugin that created this error (quilt_loader) forgot to call 'appendReportText'!
The next stacktrace is where the plugin created the error, not the actual error.'

java.lang.Throwable
        at org.quiltmc.loader.impl.gui.QuiltJsonGuiMessage.<init>(QuiltJsonGuiMessage.java:79)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.reportError(QuiltPluginManagerImpl.java:660)
        at org.quiltmc.loader.impl.plugin.BasePluginContext.reportError(BasePluginContext.java:88)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper$DependencyError.report(SolverErrorHelper.java:593)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper.reportErrors(SolverErrorHelper.java:68)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.handleSolverFailure(QuiltPluginManagerImpl.java:1452)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runSingleCycle(QuiltPluginManagerImpl.java:1348)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runInternal(QuiltPluginManagerImpl.java:1253)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.run(QuiltPluginManagerImpl.java:708)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.runPlugins(QuiltLoaderImpl.java:512)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:293)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:285)
        at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:147)
        at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:66)


-- Plugin State --

Cycle number = 1
Cycle Step = SOLVE

Loaded Plugins (2):
 - 'quilt_loader' (Builtin)
 - 'quilted_fabric_loader' (Builtin)
 ```

**Comment by TelepathicGrunt** [comment]
That looks like a quilt loader bug. Please report to quilt so they can fix it. Once fixed, if there is an actual error, then reopen this with new log that will show the true error

**Comment by Magicrafter13** [comment]
> That looks like a quilt loader bug. Please report to quilt so they can fix it. Once fixed, if there is an actual error, then reopen this with new log that will show the true error

What version of quilt loader did you use when testing this release?

**Comment by TelepathicGrunt** [comment]
I haven’t launched with quilt but even if I did, the log tells me nothing so there’s no troubleshooting I can do. You need to get quilt to fix their log so the actual issue is present if there is one so I can actual do proper troubleshooting

**Comment by TelepathicGrunt** [comment]
Looks like it is a known issue with Quilt Loader and likely has nothing to do with my mod: https://github.com/QuiltMC/quilt-loader/issues/318

**Comment by Magicrafter13** [comment]
I just checked the Modrinth page again and realized the Quilt build isn't actually *for* Quilt, my bad. I didn't notice the QFAPI/QSL dependency.
