### ISSUE TITLE
Failed to load mod file

### ISSUE THREAD

**Issue by Nycto97** [TelepathicGrunt/RepurposedStructures#294]
I'm playing on `Minecraft 1.19`, `Forge 41.1.0`, using `repurposed_structures_forge-6.3.24+1.19.2`

When adding RS to the mods folder on my server (without any other mod installed) and launching the server, it crashes and I get the following log:

`2023-08-05 02:22:01,893 main WARN Advanced terminal features are not available in this environment
[02:22:02] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 41.1.0, --fml.mcVersion, 1.19, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220607.102129]
[02:22:02] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.7 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[02:22:02] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/G:/Program%20Files/Minecraft/Forge%201.19%20Server%20Nycto/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2362!/ Service=ModLauncher Env=SERVER
[02:22:02] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file G:\Program Files\Minecraft\Forge 1.19 Server Nycto\libraries\net\minecraftforge\fmlcore\1.19-41.1.0\fmlcore-1.19-41.1.0.jar is missing mods.toml file
[02:22:02] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file G:\Program Files\Minecraft\Forge 1.19 Server Nycto\libraries\net\minecraftforge\javafmllanguage\1.19-41.1.0\javafmllanguage-1.19-41.1.0.jar is missing mods.toml file
[02:22:02] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file G:\Program Files\Minecraft\Forge 1.19 Server Nycto\libraries\net\minecraftforge\lowcodelanguage\1.19-41.1.0\lowcodelanguage-1.19-41.1.0.jar is missing mods.toml file
[02:22:02] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file G:\Program Files\Minecraft\Forge 1.19 Server Nycto\libraries\net\minecraftforge\mclanguage\1.19-41.1.0\mclanguage-1.19-41.1.0.jar is missing mods.toml file
[02:22:02] [main/ERROR] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Failed to load mod file META-INF\jarjar\mixinextras-forge-0.2.0-beta.6.jar from repurposed_structures_forge-6.3.24+1.19.2.jar
Exception in thread "main" net.minecraftforge.forgespi.locating.ModFileLoadingException: Failed to load mod file repurposed_structures_forge-6.3.24+1.19.2.jar
        at MC-BOOTSTRAP/fmlloader@1.19-41.1.0/net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator.loadModFileFrom(JarInJarDependencyLocator.java:90)
        at MC-BOOTSTRAP/JarJar@0.3.9/net.minecraftforge.jarjar.selection.JarSelector.recursivelyDetectContainedJars(JarSelector.java:144)
        at MC-BOOTSTRAP/JarJar@0.3.9/net.minecraftforge.jarjar.selection.JarSelector.detect(JarSelector.java:122)
        at MC-BOOTSTRAP/JarJar@0.3.9/net.minecraftforge.jarjar.selection.JarSelector.detectAndSelect(JarSelector.java:33)
        at MC-BOOTSTRAP/fmlloader@1.19-41.1.0/net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator.scanMods(JarInJarDependencyLocator.java:50)
        at MC-BOOTSTRAP/fmlloader@1.19-41.1.0/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:127)
        at MC-BOOTSTRAP/fmlloader@1.19-41.1.0/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:166)
        at MC-BOOTSTRAP/fmlloader@1.19-41.1.0/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.nio.file.ProviderNotFoundException: Provider "jij" not found
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:359)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
        at MC-BOOTSTRAP/fmlloader@1.19-41.1.0/net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator.loadModFileFrom(JarInJarDependencyLocator.java:83)
        ... 25 more`

**Comment by TelepathicGrunt** [comment]
1.19 cannot run 1.19.2 mods. It's an entirely different mc version and codebase. 1.19.2 had breaking changes that mods had to adapt to use. I would recommend updating all your mods to 1.19.2 and your MC as well instead as 1.19.2 is the established stable modding version for the 1.19.x series. 

Basically Jar-in-jar feature was a newer thing Forge added support to but only in 1.19.2 or newer.
