### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by SirMacro** [TelepathicGrunt/RepurposedStructures#93]
Crashed after I found a snowy tower ( short full snow ) in a snowy biome :C
Crash log:

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 5/7/21 10:23 PM
Description: Feature placement

java.lang.ClassCastException: net.minecraft.class_3233 cannot be cast to net.minecraft.class_1937
	at net.Shad0w.Allure.Blocks.Speleothem.SpeleothemBlock.method_9558(SpeleothemBlock.java:51)
	at net.minecraft.class_4970$class_4971.method_26184(class_4970.java:926)
	at com.telepathicgrunt.repurposedstructures.world.processors.RemoveFloatingBlocksProcessor.method_15110(RemoveFloatingBlocksProcessor.java:37)
	at net.minecraft.class_3499.method_16446(class_3499.java:391)
	at net.minecraft.class_3499.method_15172(class_3499.java:234)
	at net.minecraft.class_3499.method_15178(class_3499.java:210)
	at net.minecraft.class_3499.method_15182(class_3499.java:206)
	at com.telepathicgrunt.repurposedstructures.world.features.NbtDungeon.generate(NbtDungeon.java:144)
	at com.telepathicgrunt.repurposedstructures.world.features.NbtDungeon.method_13151(NbtDungeon.java:37)
	at net.minecraft.class_2975.method_12862(class_2975.java:55)
	at net.minecraft.class_2988.method_30384(class_2988.java:23)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.class_2988.method_12892(class_2988.java:22)
	at net.minecraft.class_2988.method_13151(class_2988.java:14)
	at net.minecraft.class_2975.method_12862(class_2975.java:55)
	at net.minecraft.class_1959.method_8702(class_1959.java:373)
	at net.minecraft.class_2794.method_12102(class_2794.java:220)
	at net.minecraft.class_2806.method_12151(class_2806.java:89)
	at net.minecraft.class_2806.md327c74$lambda$injectLightmapSetup$1$4(class_2806.java:546)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.Shad0w.Allure.Blocks.Speleothem.SpeleothemBlock.method_9558(SpeleothemBlock.java:51)
	at net.minecraft.class_4970$class_4971.method_26184(class_4970.java:926)
	at com.telepathicgrunt.repurposedstructures.world.processors.RemoveFloatingBlocksProcessor.method_15110(RemoveFloatingBlocksProcessor.java:37)
	at net.minecraft.class_3499.method_16446(class_3499.java:391)
	at net.minecraft.class_3499.method_15172(class_3499.java:234)
	at net.minecraft.class_3499.method_15178(class_3499.java:210)
	at net.minecraft.class_3499.method_15182(class_3499.java:206)
	at com.telepathicgrunt.repurposedstructures.world.features.NbtDungeon.generate(NbtDungeon.java:144)
	at com.telepathicgrunt.repurposedstructures.world.features.NbtDungeon.method_13151(NbtDungeon.java:37)
	at net.minecraft.class_2975.method_12862(class_2975.java:55)
	at net.minecraft.class_2988.method_30384(class_2988.java:23)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.class_2988.method_12892(class_2988.java:22)
	at net.minecraft.class_2988.method_13151(class_2988.java:14)
	at net.minecraft.class_2975.method_12862(class_2975.java:55)

-- Feature --
Details:
	Id: minecraft:decorated
	Config: < class_2986 [repurposed_structures:dungeons_snow | [minecraft:decorated net.minecraft.class_5443@4bbe3b44]] >
	Description: < class_2988 [minecraft:decorated] >
Stacktrace:
	at net.minecraft.class_1959.method_8702(class_1959.java:373)

-- Generation --
Details:
	CenterX: 220
	CenterZ: 732
	Seed: 998498073240941401
	Biome: net.minecraft.class_1959@fe2822f
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:220)
	at net.minecraft.class_2806.method_12151(class_2806.java:89)
	at net.minecraft.class_2806.md327c74$lambda$injectLightmapSetup$1$4(class_2806.java:546)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)

-- Chunk to be generated --
Details:
	Location: 220,732
	Position hash: 3143916060892
	Generator: net.minecraft.class_3754@75a24722
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)

-- Affected level --
Details:
	All players: 2 total; [class_3222['Mukidh'/53, l='ServerLevel[OakMAP]', x=-11708.52, y=25.00, z=-11797.98], class_3222['Nuclide'/455, l='ServerLevel[OakMAP]', x=3493.31, y=89.45, z=11694.99]]
	Chunk stats: ServerChunkCache: 5236
	Level dimension: minecraft:overworld
	Level spawn location: World: (-238,71,202), Chunk: (at 2,4,10 in -15,12; contains blocks -240,0,192 to -225,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 23574252 game time, 11410552 day time
	Level name: OakMAP
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 116147 (now: false), thunder time: 73342 (now: false)
	Known server brands: fabric, Fabric/Gunpowder
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:874)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.15.0-106-generic
	Java Version: 1.8.0_212, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 1746180560 bytes (1665 MB) / 3154640896 bytes (3008 MB) up to 4772593664 bytes (4551 MB)
	CPUs: 3
	JVM Flags: 6 total; -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -Xms1024M -Xmx5120M -XX:-UsePerfData
	Fabric Mods: 
		adventure-platform-fabric: adventure-platform-fabric 4.0.0-SNAPSHOT
		adventurez: AdventureZ 1.2.2
		aegis: Aegis 2.1.0
		allure: Allure 1.2.8
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		aopalliance_aopalliance: aopalliance 1.0
		architectury: Architectury 1.5.105
		autoconfig1u: Auto Config v1 Updated 3.3.1
		betterend: Better End 0.9.6-pre
		cardinal-components-base: Cardinal Components API (base) 2.7.2
		cardinal-components-entity: Cardinal Components API (entities) 2.7.2
		cardinal-components-item: Cardinal Components API (items) 2.7.2
		charm: Charm 2.3.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.19
		cloud-v1: Cloud 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-brigadier: cloud-brigadier 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-core: cloud-core 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-services: cloud-services 1.5.0-SNAPSHOT
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.9.0
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.9.0
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.9.0
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.9.0
		com_fasterxml_jackson_module_jackson-module-kotlin: jackson-module-kotlin 2.9.0
		com_google_inject_guice: guice 4.2.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		curios: Curios API 0.0.13-1.16.5
		cursedorigins: CursedOrigins 1.1.4
		ekho: Ekho 0.2.0
		enva: Environmental Armor 1.3.1
		extraalchemy: Extra Alchemy 1.4.4
		extraorigins: Extra Origins 1.16.5-11
		fabric: Fabric API 0.32.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fantasycraft: Fantasycraft 1.1.3
		fatxporbs: Fat Experience Orbs 0.0.9
		fiber: fiber 0.23.0-2
		geckolib3: Geckolib 3.0.33
		gunpowder-base: Gunpowder 0.4.3+1.16.5
		gunpowder-currency: Gunpowder Currency 1.0.2+gunpowder.0.3.7.mc.1.16.5
		gunpowder-market: Gunpowder Market 1.0.3+gunpowder.0.4.0.mc.1.16.5
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 8
		javax_inject_javax_inject: javax.inject 1
		libgui: LibGui 3.2.2+1.16.3
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.4
		minecraft: Minecraft 1.16.5
		moborigins: Mob Origins 1.4.0
		more_codecs: More Codecs 0.1.2
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		multi_item_lib: Multi Item Lib 1.2.0
		mysql_mysql-connector-java: mysql-connector-java 5.1.46
		ne-v-seti: Ne v seti 0.1.4
		net_kyori_adventure-api: adventure-api 4.7.0
		net_kyori_adventure-key: adventure-key 4.7.0
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.1.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.7.0
		net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.7.0
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.7.0
		net_kyori_examination-api: examination-api 1.1.0
		net_kyori_examination-string: examination-string 1.1.0
		netherite_plus: Netherite Plus Mod 1.4.3-1.16.5
		org_apache_logging_log4j_log4j-slf4j-impl: log4j-slf4j-impl 2.8.1
		org_jetbrains_exposed_exposed-core: exposed-core 0.29.1
		org_jetbrains_exposed_exposed-java-time: exposed-java-time 0.29.1
		org_jetbrains_exposed_exposed-jdbc: exposed-jdbc 0.29.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		org_postgresql_postgresql: postgresql 42.2.2
		org_slf4j_slf4j-api: slf4j-api 1.8.0-beta1
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.28.0
		org_yaml_snakeyaml: snakeyaml 1.26
		origins: Origins 0.7.0
		origins-classes: Origins: Classes 1.1.1
		originsplus: Origins Plus 0.0.2
		oro_config: OroArmor Config 2.0.0
		pehkui: Pehkui 2.0.0+21w14a
		phosphor: Phosphor 0.7.1+build.11
		player_roles: Player Roles 1.3.1
		playtime-tracker: Playtime Tracker 0.1.0
		ratsmischief: Rat's Mischief 1.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.5-1.10.3-fabric
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		tabtps-fabric: TabTPS 1.3.5
		toomanyorigins: TooManyOrigins 0.1.2
		voyager: Voyager 1.0.0
		xaerominimapfair: Xaero's Minimap Fair-Play 21.7.0
	Player Count: 2 / 16; [class_3222['Mukidh'/53, l='ServerLevel[OakMAP]', x=-11708.52, y=25.00, z=-11797.98], class_3222['Nuclide'/455, l='ServerLevel[OakMAP]', x=3493.31, y=89.45, z=11694.99]]
	Data Packs: vanilla, Fabric Mods, file/Artic_Fox.zip, file/Monkey_v0.4.zip, file/Panther.zip, file/TurtleMaster_Origin.zip, file/changeling.zip, file/player head drops v1.1.0.zip, file/unlock all recipes v2.0.1.zip, file/AG,+LagClear+v3.zip (incompatible), file/villager workstation highlights v1.1.0.zip, file/PhoenixUpdated.zip, file/Klini.zip, file/Poriferian_v1.1.zip, file/skunk_origin_pehkui.zip
	Is Modded: Definitely; Server brand changed to 'Fabric/Gunpowder'
	Type: Dedicated Server (map_server.txt)

**Comment by TelepathicGrunt** [comment]
Thank you for your report! You are on the githug for the forge version of repurposed structures btw. Check out the fabric github here where we already have a report about Allure's SpeleothemBlock crashing Repurposed Structures: https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/106

Grab the datapack from that issue report to turn of Allure's SpeleothemBlock feature as it seems Allure is no longer getting updates to fix their bugs. Hopefully that will help you out!
